-- =============================================================================
-- Calendar observances 2026-09-01 → 2027-12-31 (GENERATED — do not hand-edit;
-- edit rows in the admin dashboard, or re-run database/tools/generate_calendar_seed.py).
-- Computed astronomically for Hetauda; see the generator's docstring for the rules.
-- Please have the temple priest review these once against the temple's panchang.
-- Idempotent: skips any (date, English title) that already exists.
-- =============================================================================
insert into public.calendar_events
  (event_date, category, title_en, title_ne, tithi_en, tithi_ne, description_en, description_ne, is_major)
select v.event_date::date, v.category, v.title_en, v.title_ne, v.tithi_en, v.tithi_ne,
       v.description_en, v.description_ne, v.is_major
from (values
  ('2026-09-04', 'festival', 'Sri Krishna Janmashtami', 'श्रीकृष्ण जन्माष्टमी', null, null, 'Appearance day of Lord Krishna; midnight abhishekam.', 'भगवान कृष्णको जन्मोत्सव; मध्यरातमा अभिषेक।', true),
  ('2026-09-07', 'ekadashi', 'Aja Ekadashi', 'अजा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-09-11', 'amavasya', 'Shravana Amavasya', 'श्रावण औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2026-09-22', 'ekadashi', 'Parivartini Ekadashi', 'परिवर्तिनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-09-26', 'purnima', 'Bhadrapada Purnima', 'भाद्र पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2026-10-06', 'ekadashi', 'Indira Ekadashi', 'इन्दिरा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-10-10', 'amavasya', 'Bhadrapada Amavasya', 'भाद्र औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2026-10-11', 'festival', 'Ghatasthapana', 'घटस्थापना', null, null, 'First day of Bada Dashain.', 'बडा दशैंको पहिलो दिन।', true),
  ('2026-10-21', 'festival', 'Vijaya Dashami', 'विजया दशमी', null, null, 'Dashain tika day.', 'दशैंको टीका।', true),
  ('2026-10-22', 'ekadashi', 'Papankusha Ekadashi', 'पापांकुशा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-10-26', 'purnima', 'Kojagrat Purnima', 'कोजाग्रत पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2026-11-05', 'ekadashi', 'Rama Ekadashi', 'रमा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-11-09', 'festival', 'Laxmi Puja (Tihar)', 'लक्ष्मी पूजा (तिहार)', null, null, 'Worship of Goddess Lakshmi; the temple is lit with lamps.', 'देवी लक्ष्मीको पूजा; मन्दिर दीपले सजिन्छ।', true),
  ('2026-11-10', 'festival', 'Govardhan Puja', 'गोवर्धन पूजा', null, null, 'Offering to Lord Krishna as lifter of Govardhan hill.', 'गोवर्धनधारी भगवान कृष्णको पूजा।', false),
  ('2026-11-11', 'festival', 'Bhai Tika', 'भाइटीका', null, null, 'Final day of Tihar.', 'तिहारको अन्तिम दिन।', true),
  ('2026-11-21', 'ekadashi', 'Haribodhini Ekadashi', 'हरिबोधिनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', true),
  ('2026-11-24', 'purnima', 'Kartik Purnima', 'कार्तिक पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2026-12-04', 'ekadashi', 'Utpanna Ekadashi', 'उत्पन्ना एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2026-12-08', 'amavasya', 'Kartik Amavasya', 'कार्तिक औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2026-12-14', 'festival', 'Vivah Panchami', 'विवाह पञ्चमी', null, null, 'Divine wedding of Sri Rama and Sita.', 'श्रीराम र सीताको दिव्य विवाह।', true),
  ('2026-12-20', 'ekadashi', 'Vaikuntha Ekadashi', 'वैकुण्ठ एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Mokshada Ekadashi — gates of Vaikuntha open. Fasting and night-long prayers.', 'वैकुण्ठ द्वार खुल्ने दिन। उपवास र रातभरि प्रार्थना।', true),
  ('2026-12-24', 'purnima', 'Margashirsha Purnima', 'मार्गशीर्ष पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-01-03', 'ekadashi', 'Saphala Ekadashi', 'सफला एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-01-07', 'amavasya', 'Margashirsha Amavasya', 'मार्गशीर्ष औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-01-15', 'sankranti', 'Maghe Sankranti', 'माघे संक्रान्ति', null, null, 'Sun enters Makara; sesame and ghee offerings.', 'सूर्य मकर राशिमा प्रवेश; तिल र घिउ अर्पण।', true),
  ('2027-01-19', 'ekadashi', 'Putrada Ekadashi', 'पुत्रदा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-01-22', 'purnima', 'Pausha Purnima', 'पौष पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-02-02', 'ekadashi', 'Shattila Ekadashi', 'षटतिला एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-02-06', 'amavasya', 'Pausha Amavasya', 'पौष औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-02-11', 'festival', 'Shree Panchami', 'श्रीपञ्चमी', null, null, 'Vasanta Panchami.', 'वसन्त पञ्चमी।', false),
  ('2027-02-17', 'ekadashi', 'Jaya Ekadashi', 'जया एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-02-20', 'purnima', 'Magha Purnima', 'माघ पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-03-04', 'ekadashi', 'Vijaya Ekadashi', 'विजया एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-03-08', 'amavasya', 'Magha Amavasya', 'माघ औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-03-19', 'ekadashi', 'Amalaki Ekadashi', 'आमलकी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-03-21', 'festival', 'Fagu Purnima (Holi)', 'फागु पूर्णिमा (होली)', null, null, 'Festival of colours (hill date; the Terai celebrates the next day).', 'रंगको पर्व (पहाडी मिति; तराईमा भोलिपल्ट)।', true),
  ('2027-03-22', 'purnima', 'Phalguna Purnima', 'फाल्गुन पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-04-02', 'ekadashi', 'Papamochani Ekadashi', 'पापमोचनी एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-04-06', 'amavasya', 'Chaitra Amavasya', 'चैत्र औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-04-14', 'festival', 'Nepali New Year', 'नयाँ वर्ष', null, null, 'Baisakh 1 — first day of the Bikram Sambat year.', 'बैशाख १ — विक्रम संवत्को पहिलो दिन।', true),
  ('2027-04-15', 'festival', 'Sri Rama Navami', 'श्रीराम नवमी', null, null, 'Appearance day of Lord Sri Rama.', 'भगवान श्रीरामको प्राकट्य दिवस।', true),
  ('2027-04-17', 'ekadashi', 'Kamada Ekadashi', 'कामदा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-04-20', 'purnima', 'Chaitra Purnima', 'चैत्र पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-05-02', 'ekadashi', 'Varuthini Ekadashi', 'वरूथिनी एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-05-06', 'amavasya', 'Chaitra Amavasya', 'चैत्र औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-05-16', 'ekadashi', 'Mohini Ekadashi', 'मोहिनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-05-19', 'festival', 'Narasimha Jayanti', 'नृसिंह जयन्ती', null, null, 'Appearance day of Lord Narasimha.', 'भगवान नृसिंहको प्राकट्य दिवस।', true),
  ('2027-05-20', 'purnima', 'Buddha Purnima', 'बुद्ध पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2027-06-01', 'ekadashi', 'Apara Ekadashi', 'अपरा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-06-04', 'amavasya', 'Vaishakha Amavasya', 'वैशाख औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-06-14', 'ekadashi', 'Nirjala Ekadashi', 'निर्जला एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-06-18', 'purnima', 'Jyeshtha Purnima', 'ज्येष्ठ पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-06-30', 'ekadashi', 'Yogini Ekadashi', 'योगिनी एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-07-04', 'amavasya', 'Jyeshtha Amavasya', 'ज्येष्ठ औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-07-14', 'ekadashi', 'Harishayani Ekadashi', 'हरिशयनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', true),
  ('2027-07-18', 'purnima', 'Guru Purnima', 'गुरु पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2027-07-30', 'ekadashi', 'Kamika Ekadashi', 'कामिका एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-08-02', 'amavasya', 'Ashadha Amavasya', 'आषाढ औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-08-12', 'ekadashi', 'Putrada Ekadashi', 'पुत्रदा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-08-17', 'purnima', 'Janai Purnima', 'जनै पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2027-08-25', 'festival', 'Sri Krishna Janmashtami', 'श्रीकृष्ण जन्माष्टमी', null, null, 'Appearance day of Lord Krishna; midnight abhishekam.', 'भगवान कृष्णको जन्मोत्सव; मध्यरातमा अभिषेक।', true),
  ('2027-08-28', 'ekadashi', 'Aja Ekadashi', 'अजा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-08-31', 'amavasya', 'Shravana Amavasya', 'श्रावण औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-09-11', 'ekadashi', 'Parivartini Ekadashi', 'परिवर्तिनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-09-15', 'purnima', 'Bhadrapada Purnima', 'भाद्र पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-09-26', 'ekadashi', 'Indira Ekadashi', 'इन्दिरा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-09-30', 'festival', 'Ghatasthapana', 'घटस्थापना', null, null, 'First day of Bada Dashain.', 'बडा दशैंको पहिलो दिन।', true),
  ('2027-09-30', 'amavasya', 'Bhadrapada Amavasya', 'भाद्र औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-10-10', 'festival', 'Vijaya Dashami', 'विजया दशमी', null, null, 'Dashain tika day.', 'दशैंको टीका।', true),
  ('2027-10-11', 'ekadashi', 'Papankusha Ekadashi', 'पापांकुशा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-10-15', 'purnima', 'Kojagrat Purnima', 'कोजाग्रत पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2027-10-26', 'ekadashi', 'Rama Ekadashi', 'रमा एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-10-29', 'festival', 'Laxmi Puja (Tihar)', 'लक्ष्मी पूजा (तिहार)', null, null, 'Worship of Goddess Lakshmi; the temple is lit with lamps.', 'देवी लक्ष्मीको पूजा; मन्दिर दीपले सजिन्छ।', true),
  ('2027-10-30', 'festival', 'Govardhan Puja', 'गोवर्धन पूजा', null, null, 'Offering to Lord Krishna as lifter of Govardhan hill.', 'गोवर्धनधारी भगवान कृष्णको पूजा।', false),
  ('2027-10-31', 'festival', 'Bhai Tika', 'भाइटीका', null, null, 'Final day of Tihar.', 'तिहारको अन्तिम दिन।', true),
  ('2027-11-10', 'ekadashi', 'Haribodhini Ekadashi', 'हरिबोधिनी एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', true),
  ('2027-11-14', 'purnima', 'Kartik Purnima', 'कार्तिक पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', true),
  ('2027-11-24', 'ekadashi', 'Utpanna Ekadashi', 'उत्पन्ना एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-11-28', 'amavasya', 'Kartik Amavasya', 'कार्तिक औंसी', 'Amavasya', 'औंसी', null, null, false),
  ('2027-12-03', 'festival', 'Vivah Panchami', 'विवाह पञ्चमी', null, null, 'Divine wedding of Sri Rama and Sita.', 'श्रीराम र सीताको दिव्य विवाह।', true),
  ('2027-12-09', 'ekadashi', 'Mokshada Ekadashi', 'मोक्षदा एकादशी', 'Shukla Ekadashi', 'शुक्ल एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-12-13', 'purnima', 'Margashirsha Purnima', 'मार्गशीर्ष पूर्णिमा', 'Purnima', 'पूर्णिमा', 'Full moon — evening prayers and lamp offering.', 'पूर्णिमा — साँझको प्रार्थना र दीप अर्पण।', false),
  ('2027-12-23', 'ekadashi', 'Saphala Ekadashi', 'सफला एकादशी', 'Krishna Ekadashi', 'कृष्ण एकादशी', 'Fasting day for Lord Vishnu.', 'भगवान विष्णुको व्रत।', false),
  ('2027-12-27', 'amavasya', 'Margashirsha Amavasya', 'मार्गशीर्ष औंसी', 'Amavasya', 'औंसी', null, null, false)
) as v(event_date, category, title_en, title_ne, tithi_en, tithi_ne, description_en, description_ne, is_major)
where not exists (
  select 1 from public.calendar_events c
  where c.event_date = v.event_date::date and c.title_en = v.title_en
);
